using System;
using System.Linq;
using Chat.Dal.Dto;

namespace Chat.Dal.IntegrationTests.Dto
{
    public static class TestObjectBuilder
    {
        public static Chat.Dal.Dto.Room CreateRoom()
        {
            var res = new Room()
            {
                CreatedTime = new DateTime(2019, 8, 3),
                Name = "asp.net",
                Softdelete = false,
                
            };
            return res;
        }

        public static T Create<T>()
        {
            T instance = (T)Activator.CreateInstance(typeof(T));

            var props = typeof(T).GetProperties();
            foreach (var propertyInfo in props)
            {
                if (propertyInfo.Name.ToLowerInvariant() == "id")
                {
                    continue;//id should be generated by db
                }
                else if (propertyInfo.PropertyType == typeof(string))
                {
                    propertyInfo.SetValue(instance, propertyInfo.Name, null);
                }
                else if (propertyInfo.PropertyType == typeof(int))
                {
                    propertyInfo.SetValue(instance, 100500, null);
                }
                else if (propertyInfo.PropertyType == typeof(DateTime))
                {
                    propertyInfo.SetValue(instance, DateTime.UtcNow, null);
                }
            }

            return instance;
        }
    }
}