//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public int Id { get; set; }
        public string Head { get; set; }
        public string Text { get; set; }
        public System.DateTime WhenDate { get; set; }
        public System.Guid UserId { get; set; }
    }
}
