//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public long Id { get; set; }
        public string Header { get; set; }
        public string Description { get; set; }
        public Nullable<double> Cost { get; set; }
        public bool NoCost { get; set; }
        public Nullable<double> PaybackPeriod { get; set; }
        public Nullable<double> MonthlyIncome { get; set; }
    }
}
