//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public long Id { get; set; }
        public string Header { get; set; }
        public string Description { get; set; }
        public Nullable<double> Cost { get; set; }
        public bool NoCost { get; set; }
        public Nullable<double> PaybackPeriod { get; set; }
        public Nullable<double> MonthlyIncome { get; set; }
    }
}
