//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashOuts
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public double Value { get; set; }
        public System.DateTime WhenDate { get; set; }
        public string Sposob { get; set; }
        public Nullable<System.DateTime> WhenAdminEvent { get; set; }
        public int State { get; set; }
        public string Number { get; set; }
        public string Comment { get; set; }
        public int Type { get; set; }
        public string PaymentNumber { get; set; }
        public int Result { get; set; }
    }
}
