//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashIns
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public double Value { get; set; }
        public string Sposob { get; set; }
        public System.DateTime WhenDate { get; set; }
        public string AcceptedAccount { get; set; }
        public string SendAccount { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
