//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Name_Ru_ { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }
    }
}
