//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public int СomplaintType { get; set; }
        public int ObjectId { get; set; }
        public int ObjectType { get; set; }
        public System.Guid UserSender { get; set; }
        public System.Guid UserRecipier { get; set; }
        public System.DateTime Data { get; set; }
    }
}
