//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currencies
    {
        public Currencies()
        {
            this.Wallets = new HashSet<Wallets>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Acronim { get; set; }
        public System.DateTime DateAdd { get; set; }
        public bool IsValid { get; set; }
    
        public virtual ICollection<Wallets> Wallets { get; set; }
    }
}
