//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currencies
    {
        public Currencies()
        {
            this.Wallets = new HashSet<Wallets>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Acronim { get; set; }
        public System.DateTime DateAdd { get; set; }
        public bool IsValid { get; set; }
    
        public virtual ICollection<Wallets> Wallets { get; set; }
    }
}
