//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeProducts
    {
        public long Id { get; set; }
        public long AdvertId { get; set; }
        public string Comment { get; set; }
        public string WantedObject { get; set; }
        public string Header { get; set; }
        public Nullable<long> SelectedRequestId { get; set; }
    }
}
