//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoritesByCookies
    {
        public long Id { get; set; }
        public string UserCookiesId { get; set; }
        public long AdvertId { get; set; }
        public System.DateTime Created { get; set; }
    }
}
