//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Cost { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> CoordinateX { get; set; }
        public Nullable<decimal> CoordinateY { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coordinate { get; set; }
        public string Phone { get; set; }
        public int CommunicationType { get; set; }
    }
}
