//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginStat
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Ip { get; set; }
        public System.DateTime WhenDate { get; set; }
    }
}
