//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginStat
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Ip { get; set; }
        public System.DateTime WhenDate { get; set; }
    }
}
