//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsAntares
    {
        public int Id { get; set; }
        public string text { get; set; }
        public System.DateTime date { get; set; }
        public System.Guid authorId { get; set; }
        public System.DateTime createDate { get; set; }
        public bool active { get; set; }
    }
}
