//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsAntares
    {
        public int Id { get; set; }
        public string text { get; set; }
        public System.DateTime date { get; set; }
        public System.Guid authorId { get; set; }
        public System.DateTime createDate { get; set; }
        public bool active { get; set; }
    }
}
