//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public long Id { get; set; }
        public System.Guid UserIdSender { get; set; }
        public System.Guid UserIdRecepient { get; set; }
        public double Value { get; set; }
        public System.DateTime WhenDate { get; set; }
        public string Comment { get; set; }
    }
}
