//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public System.DateTime Created { get; set; }
        public string ImgUrl { get; set; }
        public int CountLikes { get; set; }
        public int TimeMinutesToCook { get; set; }
        public long UserId { get; set; }
    }
}
