//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid UserOwnerId { get; set; }
        public int RentType { get; set; }
        public int DayRentPrice { get; set; }
        public Nullable<int> HourRentPrice { get; set; }
        public Nullable<int> MinuteRentPrice { get; set; }
        public string ImgUrls { get; set; }
    }
}
