//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenderRequest
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public System.Guid ProviderId { get; set; }
        public string ProviderName { get; set; }
        public int Cost { get; set; }
        public System.Guid CustomerId { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> DateDelivered { get; set; }
        public Nullable<System.DateTime> DateWin { get; set; }
        public int TenderId { get; set; }
    }
}
