//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserViews
    {
        public long Id { get; set; }
        public int ObjectId { get; set; }
        public int Type { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime Date { get; set; }
    }
}
