//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersOpenAuthAccounts
    {
        public string ApplicationName { get; set; }
        public string ProviderName { get; set; }
        public string ProviderUserId { get; set; }
        public string ProviderUserName { get; set; }
        public string MembershipUserName { get; set; }
        public Nullable<System.DateTime> LastUsedUtc { get; set; }
    
        public virtual UsersOpenAuthData UsersOpenAuthData { get; set; }
    }
}
