//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersSearches
    {
        public long Id { get; set; }
        public string Search { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> OnlyInName { get; set; }
        public Nullable<decimal> StartPrice { get; set; }
        public Nullable<decimal> EndPrice { get; set; }
        public string City { get; set; }
        public string SortBy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public System.Guid UserId { get; set; }
    }
}
