//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersOpenAuthAccounts
    {
        public string ApplicationName { get; set; }
        public string ProviderName { get; set; }
        public string ProviderUserId { get; set; }
        public string ProviderUserName { get; set; }
        public string MembershipUserName { get; set; }
        public Nullable<System.DateTime> LastUsedUtc { get; set; }
    
        public virtual UsersOpenAuthData UsersOpenAuthData { get; set; }
    }
}
