//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoolo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallets
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public int CurrencyId { get; set; }
        public double Value { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Currencies Currencies { get; set; }
        public virtual Users Users { get; set; }
    }
}
