SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserViews](
  [Id] [bigint] IDENTITY(1,1) NOT NULL,
  [ObjectId] [int] NOT NULL,
  [Type] [int] NOT NULL,
  [UserId] [uniqueidentifier] NOT NULL,
  [Date] [datetime] NOT NULL,
 CONSTRAINT [PK_UserViews] PRIMARY KEY CLUSTERED 
(
  [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO