/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT TOP (1000) [Id]
      ,[ApplicationId]
      ,[UserId]
      ,[UserName]
      ,[IsAnonymous]
      ,[LastActivityDate]
      ,[Pwd]
      ,[PublicId]
      ,[Communication]
      ,[ReffAdd]
      ,[LastGeoposition]
      ,[Language]
      ,[Sex]
      ,[Interests]
      ,[WorkPlace]
      ,[AboutUser]
      ,[BirthDay]
      ,[UniqueUserName]
      ,[SelectedCity]
  FROM [rentoolo].[dbo].[Users]
  order by [LastActivityDate] desc